// Governance tracker sidecar emitter (GH #194; A.2 of the tracker-as-governance-sidecar
// direction). Materializes the FX862 governance PROJECTION (projectTrackerManifest over
// META_LEDGER + FEATURE_INDEX) to disk as a GENERATED sidecar so the Development Tracker
// can ride sidecar to the SHIELD governance/documentation lifecycle instead of scraping PRs.
//
// Composition (research brief .failsafe/governance/research-brief-tracker-governance-sidecar-2026-06-06.md):
//   governed repo  → this projection is the authoritative manifest source.
//   ungoverned repo → FX857 PR-scrape generator (programs.yaml) stays the fallback.
//   operator taxonomy (FX859) → layered on top of either.
//
// HARD INVARIANT (#194): this emitter NEVER reads or writes the operator's
// docs/roadmap/programs.yaml. It only writes the generated sidecar
// docs/roadmap/programs.generated.yaml. The operator's hand-curated FX859 taxonomy is
// never clobbered. The two files are distinct layers; consumption/merge is a follow-up.
//
// The core (serialize + emit) is PURE over injected deps → deterministically unit-tested.
// The Node-backed deps factory is the only I/O seam.

import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import type { TrackerManifest } from './tracker-model';
import { projectTrackerManifest } from './governance-projection';
import { resolveRepoSlug } from './manifest-sources';

// Workspace-relative keys are logical POSIX paths (forward slash); nodeSidecarDeps
// normalizes them to OS separators via path.join only at the I/O boundary. This keeps
// the keys stable + comparable across platforms (and matches injected-deps test keys).
/** The GENERATED sidecar — this emitter's only write target. */
export const GOVERNANCE_SIDECAR_RELPATH = 'docs/roadmap/programs.generated.yaml';
/** The operator's hand-curated taxonomy (FX859) — this emitter NEVER touches it. */
export const OPERATOR_MANIFEST_RELPATH = 'docs/roadmap/programs.yaml';
const META_LEDGER_RELPATH = 'docs/META_LEDGER.md';
const FEATURE_INDEX_RELPATH = 'docs/FEATURE_INDEX.md';

const BANNER =
  '# GENERATED by FailSafe — "FailSafe: Emit Governance Tracker Sidecar" (GH #194).\n'
  + '# A projection of the SHIELD governance ledger (docs/META_LEDGER.md + docs/FEATURE_INDEX.md),\n'
  + '# NOT a PR scrape. Do not hand-edit — re-emitted on governance writes. The operator taxonomy\n'
  + '# lives in docs/roadmap/programs.yaml (FX859), which this file never overwrites.\n';

/** Serialize a projected manifest to the sidecar YAML text. Pure. */
export function serializeGovernanceSidecar(manifest: TrackerManifest): string {
  return BANNER + yaml.dump(manifest, { lineWidth: 120 });
}

/** Injected I/O seam so the emit core stays pure + unit-testable. */
export interface SidecarDeps {
  /** Read a workspace-relative path; null when absent/unreadable. */
  readFile(relPath: string): string | null;
  /** Write a workspace-relative path (caller ensures parent dir exists). */
  writeFile(relPath: string, data: string): void;
  /** GitHub `owner/repo` slug, or undefined when not a GitHub repo. */
  repoSlug(): string | undefined;
  /** Plan docs from `.failsafe/governance/plans/*.md` (A.1b, #195) → programs/phases.
   *  Empty array when the dir is absent (ungoverned repo). */
  readPlans(): Array<{ slug: string; content: string }>;
}

export type SidecarStatus = 'written' | 'unchanged' | 'skipped-no-governance' | 'error';

export interface SidecarEmitResult {
  status: SidecarStatus;
  /** Workspace-relative path of the generated sidecar (always the generated path). */
  path: string;
  reason?: string;
  counts?: { rcs: number; programs: number; verticals: number; decisions: number };
}

/**
 * Project the governance manifest and emit it to the generated sidecar.
 *
 * Degrade-safe: a missing/empty META_LEDGER yields `skipped-no-governance` (ungoverned
 * repo → the FX857 generator is the fallback path, not this one); any thrown error yields
 * `error` rather than propagating. Idempotent: a re-emit with unchanged governance yields
 * `unchanged` and performs no write (prevents churn + fs.watch feedback loops).
 *
 * NEVER reads or writes OPERATOR_MANIFEST_RELPATH.
 */
export function emitGovernanceSidecar(deps: SidecarDeps): SidecarEmitResult {
  const outPath = GOVERNANCE_SIDECAR_RELPATH;
  try {
    const metaLedger = deps.readFile(META_LEDGER_RELPATH);
    if (!metaLedger || !metaLedger.trim()) {
      return { status: 'skipped-no-governance', path: outPath, reason: 'no docs/META_LEDGER.md' };
    }
    const featureIndex = deps.readFile(FEATURE_INDEX_RELPATH) ?? '';
    const slug = deps.repoSlug();

    const manifest = projectTrackerManifest({
      metaLedger,
      featureIndex,
      repo: slug && slug.trim() ? slug : undefined,
      plans: deps.readPlans(),
    });
    const counts = {
      rcs: manifest.rcs?.length ?? 0,
      programs: manifest.programs?.length ?? 0,
      verticals: manifest.verticals?.length ?? 0,
      decisions: manifest.meta?.decisions?.length ?? 0,
    };

    const next = serializeGovernanceSidecar(manifest);
    const current = deps.readFile(outPath);
    if (current === next) {
      return { status: 'unchanged', path: outPath, counts };
    }

    deps.writeFile(outPath, next);
    return { status: 'written', path: outPath, counts };
  } catch (err) {
    return { status: 'error', path: outPath, reason: String(err instanceof Error ? err.message : err) };
  }
}

/**
 * Node fs-backed deps rooted at `workspaceRoot`. The single I/O seam; the emit core above
 * is pure over this. `writeFile` creates the parent directory; reads degrade to null.
 */
export function nodeSidecarDeps(workspaceRoot: string): SidecarDeps {
  const abs = (rel: string): string => path.join(workspaceRoot, rel);
  return {
    readFile(relPath) {
      try {
        return fs.readFileSync(abs(relPath), 'utf-8');
      } catch {
        return null;
      }
    },
    writeFile(relPath, data) {
      const target = abs(relPath);
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, data, 'utf-8');
    },
    repoSlug() {
      const slug = resolveRepoSlug(workspaceRoot);
      return slug ? slug : undefined;
    },
    readPlans() {
      const dir = path.join(workspaceRoot, '.failsafe', 'governance', 'plans');
      try {
        return fs.readdirSync(dir)
          .filter((f) => f.toLowerCase().endsWith('.md'))
          .map((f) => ({ slug: f, content: fs.readFileSync(path.join(dir, f), 'utf-8') }));
      } catch {
        return [];
      }
    },
  };
}
