// Functional tests for the governance tracker sidecar emitter (GH #194; A.2).
// Pure over injected SidecarDeps → deterministic. Backend logic (no visual surface):
// the emitter materializes the FX862 projection to a GENERATED sidecar and must NEVER
// touch the operator's hand-curated docs/roadmap/programs.yaml (FX859). Render is
// unchanged (no Playwright gate); consumption of the sidecar is a follow-up (A.2b).

import { strict as assert } from 'assert';
import * as yaml from 'js-yaml';
import {
  emitGovernanceSidecar,
  serializeGovernanceSidecar,
  GOVERNANCE_SIDECAR_RELPATH,
  OPERATOR_MANIFEST_RELPATH,
  type SidecarDeps,
} from '../../../roadmap/tracker/governance-sidecar';
import type { TrackerManifest } from '../../../roadmap/tracker/tracker-model';

const LEDGER = `# META LEDGER

### Entry #424: DELIVER - v5.6.1 (Development Tracker for any repo)

**Date**: 2026-06-05
**Phase**: DELIVER
**Version**: 5.6.1
**Tag**: v5.6.1

## Decision

Release v5.6.1 delivered and published to both marketplaces.

## Content Hash

**Content Hash**: \`aaa\`

---

### Entry #425: SUBSTANTIATE - Tracker loading/freshness (#163)

**Date**: 2026-06-06
**Phase**: SUBSTANTIATE

## Decision

Reality=Promise PASS for the tracker loading + freshness work.

## Content Hash

**Content Hash**: \`bbb\`

---
`;

// The real FEATURE_INDEX is a 7-column table: | ID | Feature | Doc | Code | Test | Status | Notes |
const FEATURE_INDEX = `# Feature Index

| ID | Feature | Doc | Code | Test | Status | Notes |
| --- | --- | --- | --- | --- | --- | --- |
| FX860 | Tracker loading skeleton | docs/x.md | src/roadmap/ui/tracker/tracker-dashboard.html | src/test/a.test.ts | verified | - |
| FX864 | PR-linkage Check Run | docs/y.md | src/integrations/github-checks/pr-linkage-publish.ts | src/test/b.test.ts | verified | - |
`;

/** Spy deps recording every read/write path; seeds files from an in-memory store. */
function spyDeps(
  initial: Record<string, string> = {},
  opts: { writeThrows?: boolean; plans?: Array<{ slug: string; content: string }> } = {},
) {
  const store = new Map<string, string>(Object.entries(initial));
  const reads: string[] = [];
  const writes: Array<{ path: string; data: string }> = [];
  const deps: SidecarDeps = {
    readFile(relPath) {
      reads.push(relPath);
      return store.has(relPath) ? store.get(relPath)! : null;
    },
    writeFile(relPath, data) {
      writes.push({ path: relPath, data });
      if (opts.writeThrows) throw new Error('disk full');
      store.set(relPath, data);
    },
    repoSlug() {
      return 'MythologIQ-Labs-LLC/FailSafe';
    },
    readPlans() {
      return opts.plans ?? [];
    },
  };
  return { deps, reads, writes, store };
}

suite('roadmap/tracker governance-sidecar (A.2 — #194 sidecar emission)', () => {
  test('serializeGovernanceSidecar: banner + valid YAML round-trips to the manifest', () => {
    const manifest: TrackerManifest = {
      repo: 'o/r',
      meta: { title: 'Governed tracker', decisions: [{ decision: 'd', drivenBy: 'p', evidence: 'Entry #1' }] },
      rcs: [{ id: 'v5.6.1', state: 'prod', tag: 'v5.6.1' }],
      verticals: [{ key: 'k', name: 'K', accent: '#000' }],
      programs: [], phases: [],
    };
    const text = serializeGovernanceSidecar(manifest);
    assert.ok(text.startsWith('# GENERATED by FailSafe'), 'banner present');
    assert.ok(/GH #194/.test(text), 'cites the issue');
    const parsed = yaml.load(text.slice(text.indexOf('repo:'))) as TrackerManifest;
    assert.equal(parsed.repo, 'o/r');
    assert.equal(parsed.rcs?.[0].id, 'v5.6.1');
    assert.equal(parsed.meta?.decisions?.length, 1);
  });

  test('emit: governed repo → written to the GENERATED path, counts reflect the projection', () => {
    const { deps, writes } = spyDeps({
      [`docs/META_LEDGER.md`]: LEDGER,
      [`docs/FEATURE_INDEX.md`]: FEATURE_INDEX,
    });
    const r = emitGovernanceSidecar(deps);
    assert.equal(r.status, 'written');
    assert.equal(r.ledgerState, 'ok');
    assert.equal(r.path, GOVERNANCE_SIDECAR_RELPATH);
    assert.equal(writes.length, 1);
    assert.equal(writes[0].path, GOVERNANCE_SIDECAR_RELPATH);
    assert.ok((r.counts?.rcs ?? 0) >= 1, 'at least the one DELIVER release');
    assert.ok((r.counts?.verticals ?? 0) >= 1, 'path-coded FX rows → verticals');
    assert.ok((r.counts?.decisions ?? 0) >= 2, 'one decision per ledger entry');
  });

  test('HARD INVARIANT: never reads or writes the operator programs.yaml (FX859)', () => {
    const { deps, reads, writes } = spyDeps({
      [`docs/META_LEDGER.md`]: LEDGER,
      [`docs/FEATURE_INDEX.md`]: FEATURE_INDEX,
      // a real operator taxonomy present on disk — must be left untouched
      [OPERATOR_MANIFEST_RELPATH]: 'programs: [{ key: ops, name: Ops, accent: "#111" }]\n',
    });
    const r = emitGovernanceSidecar(deps);
    assert.equal(r.status, 'written');
    assert.ok(!reads.includes(OPERATOR_MANIFEST_RELPATH), 'operator programs.yaml never read');
    assert.ok(!writes.some((w) => w.path === OPERATOR_MANIFEST_RELPATH), 'operator programs.yaml never written');
  });

  test('idempotent: re-emit with unchanged governance → unchanged, no second write', () => {
    const { deps, writes } = spyDeps({
      [`docs/META_LEDGER.md`]: LEDGER,
      [`docs/FEATURE_INDEX.md`]: FEATURE_INDEX,
    });
    const first = emitGovernanceSidecar(deps);
    assert.equal(first.status, 'written');
    const second = emitGovernanceSidecar(deps); // store now holds the prior output
    assert.equal(second.status, 'unchanged');
    assert.equal(writes.length, 1, 'only the first emit wrote');
  });

  test('A.1b: plans feed programs/phases into the emitted manifest', () => {
    const plans = [
      { slug: 'plan-qor-a.md', content: '# Plan: Qor A\n\n**Target Version**: v5.7.0\n' },
      { slug: 'plan-qor-b.md', content: '# Plan: Qor B\n' },
      { slug: 'plan-monitor-x.md', content: '# Plan: Monitor X\n' }, // singleton theme -> Other
    ];
    const { deps, writes } = spyDeps(
      { [`docs/META_LEDGER.md`]: LEDGER, [`docs/FEATURE_INDEX.md`]: FEATURE_INDEX },
      { plans },
    );
    const r = emitGovernanceSidecar(deps);
    assert.equal(r.status, 'written');
    assert.ok((r.counts?.programs ?? 0) >= 2, 'qor theme + Other');
    const yamlText = writes[0].data;
    const parsed = yaml.load(yamlText.slice(yamlText.indexOf('meta:'))) as TrackerManifest;
    assert.ok(parsed.programs!.some((p) => p.key === 'qor'), 'qor program present');
    assert.equal(parsed.phases!.length, 3, 'one phase per plan');
  });

  test('ungoverned repo: no META_LEDGER → skipped-no-governance, no write', () => {
    const { deps, writes } = spyDeps({ [`docs/FEATURE_INDEX.md`]: FEATURE_INDEX });
    const r = emitGovernanceSidecar(deps);
    assert.equal(r.status, 'skipped-no-governance');
    assert.equal(r.ledgerState, 'unavailable');
    assert.equal(writes.length, 0);
  });

  test('present but truly empty META_LEDGER (whitespace only) → still skipped-no-governance, no write', () => {
    const { deps, writes } = spyDeps({
      [`docs/META_LEDGER.md`]: '   \n',
      [`docs/FEATURE_INDEX.md`]: FEATURE_INDEX,
    });
    const r = emitGovernanceSidecar(deps);
    assert.equal(r.status, 'skipped-no-governance');
    assert.equal(writes.length, 0);
  });

  // #233: a META_LEDGER that exists but does not parse to any entries must be reported
  // explicitly, never silently treated as "ungoverned" nor silently written as an
  // apparently-valid but empty sidecar (the same silent-degrade problem #233 closed for
  // TrackerRoute — see Myth-Tech-Forge#199/PR FailSafe#405).
  test('malformed META_LEDGER (non-empty, no parseable entries) → skipped-ledger-untrusted, no write', () => {
    const { deps, writes } = spyDeps({
      [`docs/META_LEDGER.md`]: 'not a valid governance ledger, no entries here\n',
      [`docs/FEATURE_INDEX.md`]: FEATURE_INDEX,
    });
    const r = emitGovernanceSidecar(deps);
    assert.equal(r.status, 'skipped-ledger-untrusted');
    assert.equal(r.ledgerState, 'malformed');
    assert.ok(r.reason?.includes('META_LEDGER.md'), `reason names the source: ${r.reason}`);
    assert.equal(writes.length, 0, 'never silently writes from unparseable content');
  });

  test('degrade-safe: a write failure → error result, never throws', () => {
    const { deps } = spyDeps(
      { [`docs/META_LEDGER.md`]: LEDGER, [`docs/FEATURE_INDEX.md`]: FEATURE_INDEX },
      { writeThrows: true },
    );
    let result;
    assert.doesNotThrow(() => { result = emitGovernanceSidecar(deps); });
    assert.equal(result!.status, 'error');
    assert.ok(/disk full/.test(result!.reason ?? ''));
  });
});
