/**
 * governedCommitFlow — the operator-confirmed orchestration around `commitPushOpenPr`,
 * shared by the Organize and Initialize commands. After a command applies workspace
 * edits, this asks once whether to commit+push+PR them; on "No" it records what was
 * done (and when) to the audit ledger so the changes are identified, not anonymous drift.
 *
 * The changed-path set is computed by the CALLER as a before/after `git status` diff
 * (proposal-agnostic, precise — never sweeps unrelated dirty files into the commit).
 *
 * PURE wiring over injected deps (confirm / git / ledger / clock) — testable, no vscode.
 */

import { commitPushOpenPr, type GitRunner, type GovernedCommitResult } from './governedCommit';
import type { GitHubPostFn } from '../integrations/github-checks/github-checks-client';

export interface GovernedFlowDeps {
  workspaceRoot: string;
  git: GitRunner;
  /** Operator confirmation (vscode.window.showInformationMessage in production). */
  confirm: (message: string) => Promise<boolean>;
  /** Record a declined commit to the audit ledger (LedgerManager.appendEntry in production). */
  recordDeclined: (info: { action: string; changes: string[]; at: string }) => Promise<void>;
  now: () => string;     // ISO timestamp (injected for tests)
  post?: GitHubPostFn;
  token?: string;
  apiBaseUrl?: string;
  branchPrefix?: string; // default "fix"
  base?: string;         // default "main"
}

export type GovernedFlowResult = GovernedCommitResult | { step: 'noop' } | { step: 'declined' };

const slugStamp = (iso: string): string => iso.replace(/[^0-9]/g, '').slice(0, 14);

export async function runGovernedCommitFlow(
  action: string,                 // "organize" | "initialize"
  changedPaths: string[],
  executedLabels: string[],
  deps: GovernedFlowDeps,
): Promise<GovernedFlowResult> {
  if (changedPaths.length === 0) return { step: 'noop' };

  const approved = await deps.confirm(
    `FailSafe ${action} applied ${changedPaths.length} change(s). Commit, push & open a PR for them?`,
  );
  if (!approved) {
    await deps.recordDeclined({ action, changes: executedLabels, at: deps.now() });
    return { step: 'declined' };
  }

  const branch = `${deps.branchPrefix || 'fix'}/${action}-${slugStamp(deps.now())}`;
  const bullets = executedLabels.map((l) => `- ${l}`).join('\n');
  const message = `chore(${action}): apply ${changedPaths.length} workspace change(s)\n\n${bullets}`;
  const prBody = `Automated by FailSafe **${action}** (operator-confirmed).\n\n### Changes\n${bullets}\n\n🤖 Generated by the FailSafe extension.`;

  return commitPushOpenPr(
    { workspaceRoot: deps.workspaceRoot, paths: changedPaths, branch, message, base: deps.base || 'main', prTitle: `chore(${action}): workspace cleanup`, prBody },
    { git: deps.git, post: deps.post, token: deps.token, apiBaseUrl: deps.apiBaseUrl },
  );
}
