/**
 * tracker-manifest-command — registers `failsafe.generateTrackerManifest` (GH #174).
 *
 * Scaffolds a Development Tracker planning manifest (docs/roadmap/programs.yaml)
 * from the repo's merged PRs + CHANGELOG, so a repo without a hand-authored
 * manifest gets a real, detailed tracker (programs, phases, verticals, decisions)
 * instead of a bare timeline. The output is an explicitly-labelled DRAFT the
 * operator refines. Never overwrites an existing manifest without confirmation.
 */

import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import { gatherManifestSources, gatherBicameralBriefs } from '../roadmap/tracker/manifest-sources';
import { generateTrackerManifest } from '../roadmap/tracker/manifest-generator';
import { enrichManifestWithBicameral } from '../roadmap/tracker/manifest-bicameral';
import type { BicameralMcpClient } from '../integrations/bicameral';

export function registerGenerateTrackerManifestCommand(
  context: vscode.ExtensionContext,
  workspaceRoot: string,
  /** Layer 3: resolve the live Bicameral client (null when not connected). */
  getBicameralClient: () => BicameralMcpClient | null = () => null,
): void {
  context.subscriptions.push(
    vscode.commands.registerCommand('failsafe.generateTrackerManifest', async () => {
      const target = path.join(workspaceRoot, 'docs', 'roadmap', 'programs.yaml');
      if (fs.existsSync(target)) {
        const choice = await vscode.window.showWarningMessage(
          'docs/roadmap/programs.yaml already exists. Overwrite it with a freshly generated draft?',
          { modal: true },
          'Overwrite',
        );
        if (choice !== 'Overwrite') return;
      }

      const sources = await vscode.window.withProgress(
        { location: vscode.ProgressLocation.Notification, title: 'FailSafe: gathering merged PRs + CHANGELOG…' },
        async () => gatherManifestSources(workspaceRoot),
      );
      if (!sources.repo) {
        await vscode.window.showWarningMessage('No GitHub origin remote found — cannot generate a tracker manifest from PRs.');
        return;
      }
      if (!sources.prs.length && !sources.changelog.trim()) {
        await vscode.window.showWarningMessage(`No merged PRs (via gh) or CHANGELOG found for ${sources.repo}.`);
        return;
      }

      const base = generateTrackerManifest(sources);
      // Layer 3: deepen with the Bicameral decision graph when connected.
      const briefs = await vscode.window.withProgress(
        { location: vscode.ProgressLocation.Notification, title: 'FailSafe: enriching from Bicameral decisions (if connected)…' },
        async () => gatherBicameralBriefs(getBicameralClient(), workspaceRoot),
      );
      const enriched = briefs.length;
      const manifest = enriched ? enrichManifestWithBicameral(base, briefs) : base;
      const banner = '# Generated by FailSafe — "FailSafe: Generate Tracker Manifest" (GH #174).\n'
        + `# A DRAFT from merged PRs + CHANGELOG${enriched ? ' + Bicameral decisions' : ''}: review + refine.\n`;
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, banner + yaml.dump(manifest, { lineWidth: 120 }), 'utf-8');

      const open = await vscode.window.showInformationMessage(
        `Generated docs/roadmap/programs.yaml — ${manifest.programs?.length ?? 0} programs, `
        + `${manifest.phases?.length ?? 0} phases, ${manifest.verticals?.length ?? 0} verticals`
        + `${enriched ? ', Bicameral-enriched' : ''}. Refine it, then reload the Development Tracker.`,
        'Open',
      );
      if (open === 'Open') {
        const doc = await vscode.workspace.openTextDocument(target);
        await vscode.window.showTextDocument(doc);
      }
    }),
  );
}
